using FORGE.Core.Interfaces;

namespace FORGE.Compilation.Interfaces;

/// <summary>
/// Compiles a C# source string into a live <see cref="IStrategy"/> instance
/// via the Roslyn pipeline, with AST validation and sandbox isolation.
/// </summary>
public interface IRoslynCompiler
{
    /// <summary>
    /// Parses, validates, compiles, and instantiates an <see cref="IStrategy"/> from raw C# source code.
    /// </summary>
    /// <param name="sourceCode">C# source code generated by an <see cref="ICodeGenerator"/>.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A live <see cref="IStrategy"/> instance loaded in an isolated <c>AssemblyLoadContext</c>.</returns>
    /// <exception cref="CompilationException">Thrown when the source code fails AST validation or Roslyn compilation.</exception>
    Task<IStrategy> CompileAsync(string sourceCode, CancellationToken ct = default);
}
